invenetory/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main,add_item_ajax,delete_item_ajax,create_item_flutter,show_data_user
from main.views import show_main, create_item, show_xml, show_json, show_xml_by_id, show_json_by_id,show_html
from main.views import register,login_user,logout_user,increase_item_amount,decrease_item_amount,delete_item
app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-item', create_item, name='create_item'),
    path('xml/',show_xml,name='show_xml'),
    path('html/',show_html,name='show_html'),
    path('json/',show_json,name='show_json'),
    path('xml/<int:id>/',show_xml_by_id,name='show_xml_by_id'),
    path('json/<int:id>/',show_json_by_id,name='show_json_by_id'),
    path('register/',register,name='register'),
    path('login/',login_user,name='login'),
    path('logout/',logout_user,name='logout'),
    path('increase_item_amount/<int:id>/',increase_item_amount,name='increase_item_amount'),
    path('decrease_item_amount/<int:id>/',decrease_item_amount,name='decrease_item_amount'),
    path('delete_item/<int:id>/',delete_item,name='delete_item'),
    path('delete_item_ajax/<int:id>/',delete_item_ajax,name='delete_item_ajax'),
    path('add-item-ajax/', add_item_ajax, name='add_item_ajax'),
    path('create-flutter/', create_item_flutter, name='create_item_flutter'),
    path('user_data/',show_data_user,name='show_data_user'),
    
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    name = models.CharField(max_length=255)
    amount =  models.IntegerField()
    description = models.TextField()
    code = models.IntegerField()
    price = models.IntegerField()
    

main/forms.py
from django.forms import ModelForm,TextInput
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description","code","price"]

main/views.py
from main.forms import ItemForm
from main.models import Item
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse,HttpResponseNotFound,JsonResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
import datetime 
import json


@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user=request.user)
    context = {
        'nama_mahasiswa': request.user.username.capitalize(),
        'kelas': 'D',
        'items':items,
        'last_login':request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))
    
    context = {'form': form}
    return render(request, "create_item.html", context)

def show_html(request):
    items = Item.objects.filter(user=request.user)
    context = {'items':items}
    return render(request,"show_html.html",context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml",data),content_type = "application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json",data),content_type= "application/json")

def show_xml_by_id(request,id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml",data),content_type="application/xml")

def show_json_by_id(request,id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json",data),content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login',str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def increase_item_amount(request,id):
    item = Item.objects.get(id=id)
    item.amount +=1
    item.save()
    return HttpResponseRedirect(reverse('main:show_html'))

def decrease_item_amount(request,id):
    item = Item.objects.get(id=id)
    if item.amount>0:
        item.amount -=1
        item.save()
    return HttpResponseRedirect(reverse('main:show_html'))

def delete_item(request,id):
    item  = Item.objects.get(id=id)
    if item.user == request.user:
        item.delete()
        return HttpResponseRedirect(reverse('main:show_html'))

@csrf_exempt
def add_item_ajax(request):
    if request.method == 'POST':
        user = request.user
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        code  = request.POST.get("code")
        price = request.POST.get("price")
        

        new_item = Item(user=user,name=name,amount=amount,code=code, description=description, price=price)
        new_item.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def delete_item_ajax(request,id):
    if request.method == 'POST':
        item = Item.objects.get(id=id)
        if item.user == request.user:
            item.delete()
            return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def create_item_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_item = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = data["amount"],    
            description = data["description"],
            code = int(data["code"]),
            price = int(data["price"]),
        )

        new_item.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    
def show_data_user(request):
    data = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json",data),content_type= "application/json")

main/templates/create_item.html
{% extends 'base.html' %} {% block content %}
<div
  class="flex flex-col items-center text-white t w-full bg-[#C08261] min-h-screen"
>
  <h5 class="text-3xl text-[#630000] font-bold text-center mt-10 mb-14">
    Add New Item
  </h5>

  <div class="mr-20 text-black mb-16">
    <a href="{% url 'main:show_main' %}">
      <button
        class="text-black font-semibold rounded-lg bg-[#9A3B3B] px-2 mb-4 hover:bg-[#D3D3D3]"
      >
        Back to Main Menu
      </button>
      
    </a>
    <form method="POST">
      {% csrf_token %}
      <table>
        {{ form.as_table }}
        <tr>
          <td></td>
          <td>
            <input
              class="cursor-pointer text-black font-semibold mt-10 rounded-lg px-5 py-2 bg-[#9A3B3B]
               hover:bg-[#D3D3D3]" type="submit" value="Add Item"
            />
          </td>
        </tr>
      </table>
    </form>
  </div>
</div>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<div class="login bg-[#C08261] min-h-screen flex flex-col items-center">

    <div class="flex flex-col text-center items-center gap-6 text-center bg-[#BA704F] px-32 py-10 my-32 mr-4">
        <h1 class="text-3xl font-semibold">Login Here!</h1>

        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>

                <tr>    
                    <td>Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>

                <tr>
                    <td></td>
                    
                    <td >
                        <input class="text-black font-semibold mt-6 rounded-lg px-5 py-2 bg-[#9A3B3B]" 
                        type="submit" value="Login"/>
                    </td>
                </tr>
            </table>
        </form>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <p>Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>
    </div>
</div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %} 

{% block content %}
<div class="flex flex-col min-h-screen bg-[#C08261]">
    <div class="text-white  flex flex-col">
        <div class="mt-2 mx-10 ">
            
            <h5 class="text-[#630000] text-6xl font-extrabold">Invenetory</h5>
            <h2 class="mt-4 text-4xl font-bold text-[#630000]">Your Best Inventory App</h2>
        </div>
    </div>
    
    <div class="w-full px-10 my-10">
        <div class="pl-6  ">
            <h5 class="text-2xl text-[#493323] font-semibold">Hai, {{nama_mahasiswa}}</h5>
            <h1 class="text-xl text-[#493323] font-semibold">Kelas PBP {{kelas}}</h1>
            <h1 class="text-xl text-[#493323] font-semibold">Last login: {{last_login}}</h1>
            
            <br />
            <a href="{% url 'main:logout' %}">
                <button class="text-black font-semibold rounded-lg bg-[#9A3B3B] py-2 px-2 mx-6
                hover:bg-[#D3D3D3]">
                    Logout
                </button>
            </a>
            
            
        <div class="text-center mt-10 h-full">
            <p class="text-xl font-semibold text-[#493323] mb-6 ">You have {{items|length}} items here</p>
            <div class="mt-8 text-center items-center">
                <a href="{% url 'main:create_item' %}">
                    <button class="text-black font-semibold rounded-lg bg-[#9A3B3B] py-2 px-2 mx-6
                    hover:bg-[#D3D3D3]">
                        Add New Item - No AJAX
                    </button>
                </a>
                <a href="{% url 'main:show_html' %}">
                    <button class="text-black font-semibold rounded-lg bg-[#9A3B3B] py-2 px-2 mx-6
                    hover:bg-[#D3D3D3]">
                        Show Items
                    </button>
                </a>
            </div>
            
            
        </div>
    </div>
        
        </div>
    </div>
    
</div>
</div>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  

<div class = "login bg-[#C08261] min-h-screen flex flex-col items-center">
    <div class="flex flex-col items-center gap-6 text-center bg-[#BA704F] px-32 py-10 my-24">
        <h1 class="text-3xl font-semibold">Register</h1>
     

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" class="text-black font-semibold mt-6 rounded-lg px-5 py-2 bg-[#9A3B3B]" 
                        name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}
    </div>
</div>  

{% endblock content %}

main/templates/show_html.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="flex flex-col pl-12  py-12 min-h-screen text-black bg-[#C08261]">
  <h2 class="text-3xl text-[#630000] font-bold mb-8">Your Items</h2>

  <div id="card_item" class="flex flex-wrap mb-2 items-center mx-12">




  </div>

  <div class="flex flex-row mx-12 my-4">
    <a href="{% url 'main:show_main' %}">
      <button class="text-black font-semibold rounded-lg bg-[#9A3B3B] py-2 px-4 mx-2 hover:bg-[#D3D3D3]">
        Back to Main Menu
      </button>
    </a>
    <a href="{% url 'main:create_item' %}">
      <button class="text-black font-semibold rounded-lg bg-[#9A3B3B] py-2 px-4 mx-2 hover:bg-[#D3D3D3]">
        Add Items - No AJAX
      </button>
    </a>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header bg-[#630000] text-white">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Item</h1>
            <button type="button" class="btn-close text-white" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form id="form" onsubmit="return false;">
              {% csrf_token %}
              <div class="mb-3">
                <label for="name" class="col-form-label">Name:</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Enter the item name">
              </div>
              <div class="mb-3">
                <label for="price" class="col-form-label">Amount:</label>
                <input type="number" class="form-control" id="amount" name="amount" placeholder="Enter the item amount">
              </div>
              <div class="mb-3">
                <label for="description" class="col-form-label">Description:</label>
                <textarea class="form-control" id="description" name="description"
                  placeholder="Enter the item description"></textarea>
              </div>
              <div class="mb-3">
                <label for="description" class="col-form-label">Code:</label>
                <textarea class="form-control" id="code" name="code" placeholder="Enter the item code"></textarea>
              </div>
              <div class="mb-3">
                <label for="description" class="col-form-label">Price:</label>
                <textarea class="form-control" id="price" name="price" placeholder="Enter the item price"></textarea>
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="rounded-lg text-white bg-[#630000] px-4 py-2 mx-2"
              data-bs-dismiss="modal">Close</button>
            <button type="button" id="button_add" class="rounded-lg text-white bg-[#630000] px-4 py-2 mx-2"
            data-bs-dismiss="modal">Add Item</button>
          </div>
        </div>
      </div>
    </div>

    <button type="button" class="text-black font-semibold rounded-lg bg-[#9A3B3B] py-2 px-4 mx-2 hover:bg-[#D3D3D3]"
      data-bs-toggle="modal" data-bs-target="#exampleModal">Add Item by AJAX</button>
  </div>
</div>
</div>

<script>
  async function getItems() {
    return fetch("{% url 'main:show_json' %}").then((res) => res.json())
  }

  async function refreshItems() {
    document.getElementById("card_item").innerHTML = ""
    const items = await getItems()
    let htmlString = ""
    items.forEach((item) => {
      htmlString += `\n <div class="flex flex-col bg-[#FAF2D3] shadow-lg rounded-lg mx-4 my-4 p-4 last:bg-yellow-300 hover:bg-[#D3D3D3] transition-all duration-300 w-[280px] h-[180px]
      break-words">

              <p class="text-xl font-semibold">${item.fields.name}</p>
              <p>${item.fields.code} - ${item.fields.description}</p>
              <p>Price: ${item.fields.price}</p>
              <p>Stock: ${item.fields.amount}</p>
              <div class="flex flex-row mt-2 gap-4">
                <a onClick="deleteItem(${item.pk});">
                  <i class="fas fa-trash-alt text-red-500  cursor-pointer hover:text-red-700"></i>
              </a>
        
                <a href="/increase_item_amount/${item.pk}/">
                  <i class="fas fa-plus-circle text-green-500  cursor-pointer hover:text-green-700"></i>
                </a>
        
                <a href="/decrease_item_amount/${item.pk}/">
                  <i class="fas fa-minus-circle text-blue-500  cursor-pointer hover:text-blue-700"></i>
                </a>
        
              </div>
            </div>
            
            </div>`
    })

    document.getElementById("card_item").innerHTML = htmlString
  }

  refreshItems()

 function addItems() {
    fetch("{% url 'main:add_item_ajax' %}", {
      method: "POST",
      body: new FormData(document.querySelector('#form'))
    }).then(refreshItems)
 
    document.getElementById("form").reset()
    return false
  }
  document.getElementById("button_add").onclick = addItems

  function deleteItem(itemId) {
    fetch(`/delete_item_ajax/${itemId}/`, {
      method: "POST",
    }).then(refreshItems);
  }


</script>


{% endblock %}